language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 0dc0b023d5641d76ca0cf6d16ee9a93ecd19965d
 local_dir: dist
 on:
   branch: master
